# Generated by Django 5.1.5 on 2025-02-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
